version: '3.7'
services:
  cas_management_server:
    build: 
      context: ${CAS_MANAGEMENT_PATH:-.}
    ports:
      - "8444:8443"
      # - "8080:8080"
    volumes: 
      - type: bind
        source: ${CAS_MANAGEMENT_PATH:-.}/management.yml
        target: /etc/cas/config/management.yml
        read_only: true
    environment:
      CAS_DOMAIN_NAME: ${CAS_DOMAIN_NAME}
