version: '3.7'
services:
  cas_server:
    build: 
      context: ${CAS_OVERLAY_PATH:-.}
    environment:
      RESOURCE_PATH: ${RESOURCE_PATH}
      SERVICES_PATH: ${SERVICES_PATH}
      CONFIG_PATH: ${CONFIG_PATH}
      CONFIG_PROPERTIES_PATH: ${CONFIG_PROPERTIES_PATH}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      CAS_DOMAIN_NAME: ${CAS_DOMAIN_NAME}
    volumes:
      - type: bind
        source: ${CAS_OVERLAY_PATH:-.}/cas.yml
        target: ${CONFIG_PATH:-.}/${CAS_OVERLAY}.yml
        read_only: true
      - type: bind
        source: ${CAS_OVERLAY_PATH:-.}/gradle.properties
        target: /cas-overlay/gradle.properties
        read_only: true
      # - type: bind
      #   source: ${CAS_OVERLAY_PATH:-.}/src
      #   target: /cas-overlay/src
      #   read_only: true