version: '3.7'
services:
  cas:
    build: 
      context: ${CAS_OVERLAY_PATH:-.}
    ports:
      - "8443:8443"
      - "8080:8080"
    environment:
      RESOURCE_PATH: ${RESOURCE_PATH}
      SERVICES_PATH: ${SERVICES_PATH}
      CONFIG_PATH: ${CONFIG_PATH}
      CONFIG_PROPERTIES_PATH: ${CONFIG_PROPERTIES_PATH}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    volumes:
      - type: bind
        source: ${CAS_OVERLAY_PATH:-.}/cas.yml
        target: ${CONFIG_PATH:-.}/${CAS_OVERLAY}.yml
        read_only: true
    networks:
      default:
        aliases:
          - 127.0.0.1