version: '3.7'
services:
  cas_server:
    volumes: 
      - type: bind
        source: ${PROTOCOL_OAUTH2_PATH:-.}/cas.yml
        target: ${CONFIG_PATH:-.}/${PROTOCOL_OAUTH2}.yml
        read_only: true
      - type: bind
        source: ${PROTOCOL_OAUTH2_PATH:-.}/build.gradle
        target: ${BUILD_GRADLE_DEPENDENCIES_PATH:-.}/${PROTOCOL_OAUTH2_PATH:-.}/build.gradle
        read_only: true
    environment:
      PROTOCOL_OAUTH2_PATH: ${PROTOCOL_OAUTH2_PATH}