version: '3.7'
services:
  cas:
    volumes: 
      - type: bind
        source: ${AUTHENTICATION_ATTRIBUTE_MYSQL_PATH:-.}/cas.yml
        target: ${CONFIG_PROPERTIES_PATH:-.}/${AUTHENTICATION_ATTRIBUTE_MYSQL_PATH:-.}/cas.yml
      - type: bind
        source: ${AUTHENTICATION_ATTRIBUTE_MYSQL_PATH:-.}/build.gradle
        target: ${BUILD_GRADLE_DEPENDENCIES_PATH:-.}/${AUTHENTICATION_ATTRIBUTE_MYSQL_PATH:-.}/build.gradle
    environment:
     - AUTHENTICATION_ATTRIBUTE_MYSQL=${AUTHENTICATION_ATTRIBUTE_MYSQL}
  authentication_attribute_mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: ${AUTHENTICATION_ATTRIBUTE_MYSQL}
      MYSQL_ROOT_PASSWORD: ThisIsThePasswordForRoot
    volumes: 
      - type: bind
        source:  ${AUTHENTICATION_ATTRIBUTE_MYSQL_PATH:-.}/init.sql
        target: /docker-entrypoint-initdb.d/${AUTHENTICATION_ATTRIBUTE_MYSQL}-init.sql
    hostname: ${AUTHENTICATION_ATTRIBUTE_MYSQL}
    networks:
      default:
        aliases:
          - ${AUTHENTICATION_ATTRIBUTE_MYSQL}