version: '3.7'
services:
  cas:
    volumes: 
      - type: bind
        source: ./authentication/accept-users/config/cas.properties
        target: /etc/cas/config/accept-users-authentication-cas.properties
