version: '3.7'
services:
  cas:
    volumes: 
      - type: bind
        source: ${AUTHENTICATION_MONGODB_PATH:-.}/cas.yml
        target: ${CONFIG_PROPERTIES_PATH:-.}/${AUTHENTICATION_MONGODB_PATH:-.}/cas.yml
      - type: bind
        source: ${AUTHENTICATION_MONGODB_PATH:-.}/build.gradle
        target: ${BUILD_GRADLE_DEPENDENCIES_PATH:-.}/${AUTHENTICATION_MONGODB_PATH:-.}/build.gradle
    environment:
     - AUTHENTICATION_MONGODB=${AUTHENTICATION_MONGODB}
  authentication_mongodb:
    image: mongo:4
    expose:
      - 27017
    environment:
      MONGO_INITDB_DATABASE: ${AUTHENTICATION_MONGODB}
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ThisIsThePasswordForRoot
      AUTHENTICATION_MONGODB: ${AUTHENTICATION_MONGODB}
    volumes: 
      - type: bind
        source:  ${AUTHENTICATION_MONGODB_PATH:-.}/init.js
        target: /docker-entrypoint-initdb.d/${AUTHENTICATION_MONGODB}-init.js
    hostname: ${AUTHENTICATION_MONGODB}
    networks:
      default:
        aliases:
          - ${AUTHENTICATION_MONGODB}