version: '3.7'
services:
  cas_server:
    volumes:
      - type: bind
        source: ${OTHER_CLIENT_SAML2_PHP_ONELOGIN_CLIENT_PATH:-.}/cas.yml
        target: ${CONFIG_PATH:-.}/${OTHER_CLIENT_SAML2_PHP_ONELOGIN_CLIENT}.yml
        read_only: true
      - type: bind
        source: ${OTHER_CLIENT_SAML2_PHP_ONELOGIN_CLIENT_PATH:-.}/service.json
        target: ${SERVICES_PATH:-.}/${OTHER_CLIENT_SAML2_PHP_ONELOGIN_CLIENT_NAME}.json
        read_only: true
      - type: bind
        source: ${OTHER_CLIENT_SAML2_PHP_ONELOGIN_CLIENT_PATH:-.}/onelogin-sp.xml
        target: ${RESOURCE_PATH:-.}/onelogin-sp.xml
        read_only: true
      - type: bind
        source: ${OTHER_CLIENT_SAML2_PHP_ONELOGIN_CLIENT_PATH:-.}/cas-saml
        target: ${SAML_PATH:-.}
        read_only: true
  other_client_saml2_php_onelogin_client:
    build: ${OTHER_CLIENT_SAML2_PHP_ONELOGIN_CLIENT_PATH:-.}/.
    ports:
      - target: 443
        published: 60000
    volumes:
      # - type: bind
      #   source: ${OTHER_CLIENT_SAML2_PHP_ONELOGIN_CLIENT_PATH:-.}/simplesamlphp-config
      #   target: /var/onelogin/config
      #   read_only: true
      # - type: bind
      #   source: ${OTHER_CLIENT_SAML2_PHP_ONELOGIN_CLIENT_PATH:-.}/simplesamlphp-metadata
      #   target: /var/onelogin/metadata
      #   read_only: true
      - type: bind
        source: ${OTHER_CLIENT_SAML2_PHP_ONELOGIN_CLIENT_PATH:-.}/index.php
        target: /var/www/html/index.php
        read_only: true
      # - type: bind
      #   source: ${OTHER_CLIENT_SAML2_PHP_ONELOGIN_CLIENT_PATH:-.}/attrs.php
      #   target: /var/www/html/attrs.php
      #   read_only: true
      - type: bind
        source: ${OTHER_CLIENT_SAML2_PHP_ONELOGIN_CLIENT_PATH:-.}/metadata.php
        target: /var/www/html/metadata.php
        read_only: true
      - type: bind
        source: ${OTHER_CLIENT_SAML2_PHP_ONELOGIN_CLIENT_PATH:-.}/settings.php
        target: /var/www/html/settings.php
        read_only: true

      - type: bind
        source: ${OTHER_CLIENT_SAML2_PHP_ONELOGIN_CLIENT_PATH:-.}/cas_private.pem
        # This is the default for Apache, don't change it
        target: /etc/ssl/private/ssl-cert-snakeoil.key 
        read_only: true
      - type: bind
        source: ${OTHER_CLIENT_SAML2_PHP_ONELOGIN_CLIENT_PATH:-.}/cas_public.crt
        # This is the default for Apache, don't change it
        target: /etc/ssl/certs/ssl-cert-snakeoil.pem
        read_only: true
    environment:
      CAS_DOMAIN_NAME: ${CAS_DOMAIN_NAME}        