version: '3.7'
services:
  cas_server:
    volumes: 
      - type: bind
        source: ${PROTOCOL_OIDC_PATH:-.}/cas.yml
        target: ${CONFIG_PATH:-.}/${PROTOCOL_OIDC}.yml
        read_only: true
      - type: bind
        source: ${PROTOCOL_OIDC_PATH:-.}/build.gradle
        target: ${BUILD_GRADLE_DEPENDENCIES_PATH:-.}/${PROTOCOL_OIDC_PATH:-.}/build.gradle
        read_only: true
    environment:
      PROTOCOL_OIDC_PATH: ${PROTOCOL_OIDC_PATH}