version: '3.7'
services:
  cas_server:
    volumes: 
      - type: bind
        source: ${AUTHENTICATION_OPENLDAP_PATH:-.}/cas.yml
        target: ${CONFIG_PATH:-.}/${AUTHENTICATION_OPENLDAP}.yml
        read_only: true
      - type: bind
        source: ${AUTHENTICATION_OPENLDAP_PATH:-.}/build.gradle
        target: ${BUILD_GRADLE_DEPENDENCIES_PATH:-.}/${AUTHENTICATION_OPENLDAP_PATH:-.}/build.gradle
        read_only: true
    environment:
      AUTHENTICATION_OPENLDAP: ${AUTHENTICATION_OPENLDAP}
    depends_on:
      - authentication_openldap
  authentication_openldap:
    image: osixia/openldap:1.3.0
    command: --copy-service --loglevel debug
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.org"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "false"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
      - type: bind
        source: ${AUTHENTICATION_OPENLDAP_PATH:-.}/add-casuser-user.ldif
        target: /container/service/slapd/assets/config/bootstrap/ldif/custom/add-casuser-user.ldif
        read_only: true
      - type: bind
        source: ${AUTHENTICATION_OPENLDAP_PATH:-.}/add-openldap-user.ldif
        target: /container/service/slapd/assets/config/bootstrap/ldif/custom/add-openldap-user.ldif
        read_only: true
    expose:
      - 389
      - 636
    hostname: ${AUTHENTICATION_OPENLDAP}
    networks:
      default:
        aliases:
          - ${AUTHENTICATION_OPENLDAP}
  # Enabled this if you want to add / delete to your LDAP
  phpldapadmin:
    command: "--loglevel debug"
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ${AUTHENTICATION_OPENLDAP}
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8081:80"
    depends_on:
      - authentication_openldap