version: '3.7'
services:
  cas:
    volumes: 
      - type: bind
        source: ${AUTHENTICATION_OPENLDAP_PATH:-.}/cas.yml
        target: ${CONFIG_PROPERTIES_PATH:-.}/${AUTHENTICATION_OPENLDAP_PATH:-.}/cas.yml
      - type: bind
        source: ${AUTHENTICATION_OPENLDAP_PATH:-.}/build.gradle
        target: ${BUILD_GRADLE_DEPENDENCIES_PATH:-.}/${AUTHENTICATION_OPENLDAP_PATH:-.}/build.gradle
    environment:
      AUTHENTICATION_OPENLDAP: ${AUTHENTICATION_OPENLDAP}
    depends_on:
      - authentication_openldap
  authentication_openldap:
    #container_name: openldap
    image: osixia/openldap:1.3.0
    command: --copy-service --loglevel debug
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.org"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "false"
      # LDAP_TLS_CRT_FILENAME: "ldap.crt"
      # LDAP_TLS_KEY_FILENAME: "ldap.key"
      # LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      # LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      # LDAP_TLS_ENFORCE: "false"
      # LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      # LDAP_TLS_PROTOCOL_MIN: "3.1"
      # LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
      - type: bind
        source: ${AUTHENTICATION_OPENLDAP_PATH:-.}/init.ldif
        target: /container/service/slapd/assets/config/bootstrap/ldif/init.ldif
        read_only: true
    ports:
      - "389:389"
      - "636:636"
    #domainname: "example.org" # important: same as hostname
    #hostname: "example.org"
    hostname: ${AUTHENTICATION_OPENLDAP}
    networks:
      default:
        aliases:
          - ${AUTHENTICATION_OPENLDAP}
  phpldapadmin:
    command: "--loglevel debug"
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ${AUTHENTICATION_OPENLDAP}
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8081:80"
    depends_on:
      - authentication_openldap