version: '3.7'
services:
  javacasclient:
    build: ${CLIENT_JAVACASCLIENT_PATH:-.}/.
    ports:
      - target: 9443
        published: 52525
    volumes:
      - type: bind
        source: ${CLIENT_JAVACASCLIENT_PATH:-.}/web.xml
        target: /javacasclient/src/main/webapp/WEB-INF/web.xml
        read_only: true
      - type: bind
        source: ${CLIENT_JAVACASCLIENT_PATH:-.}/pom.xml
        target: /javacasclient/pom.xml
        read_only: true
