version: '3.7'
services:
  cas_server:
    volumes: 
      - type: bind
        source: ${TICKET_REGISTRY_REDIS_PATH:-.}/cas.yml
        target: ${CONFIG_PATH:-.}/${TICKET_REGISTRY_REDIS}.yml
        read_only: true
      - type: bind
        source: ${TICKET_REGISTRY_REDIS_PATH:-.}/build.gradle
        target: ${BUILD_GRADLE_DEPENDENCIES_PATH:-.}/${TICKET_REGISTRY_REDIS_PATH:-.}/build.gradle
        read_only: true
    environment:
      TICKET_REGISTRY_REDIS: ${TICKET_REGISTRY_REDIS}
  ticket_registry_redis:
    image: redis:5
    expose:
      - 6379
    command: redis-server --requirepass ThisIsThePasswordForRedis
    # environment:
    #   MONGO_INITDB_DATABASE: ${TICKET_REGISTRY_REDIS}
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: ThisIsThePasswordForRoot
    #   TICKET_REGISTRY_REDIS: ${TICKET_REGISTRY_REDIS}
    hostname: ${TICKET_REGISTRY_REDIS}
    networks:
      default:
        aliases:
          - ${TICKET_REGISTRY_REDIS}