version: '3.7'
services:
  cas:
    volumes: 
      - type: bind
        source: ${AUTHENTICATION_JSON_WHITELIST_PATH:-.}/cas.properties
        #target: /etc/cas/config/json-whitelist-authentication-cas.properties
        target: /etc/cas/config/${AUTHENTICATION_JSON_WHITELIST}cas.properties
      - type: bind
        source: ${AUTHENTICATION_JSON_WHITELIST_PATH:-.}/sample.json
        target: /etc/cas/resources/json-whitelist-authentication-sample.json
      - type: bind
        source: ${AUTHENTICATION_JSON_WHITELIST_PATH:-.}/build.gradle
        target: ${BUILD_GRADLE_DEPENDENCIES_PATH:-.}/${AUTHENTICATION_JSON_WHITELIST}build.gradle