version: '3.7'
services:
  cas:
    volumes: 
      - type: bind
        source: ${AUTHENTICATION_JSON_WHITELIST_PATH:-.}/cas.yml
        target: ${CONFIG_PATH:-.}/${AUTHENTICATION_JSON_WHITELIST}.yml
        read_only: true
      - type: bind
        source: ${AUTHENTICATION_JSON_WHITELIST_PATH:-.}/authenticate.json
        target: ${RESOURCE_PATH:-.}/${AUTHENTICATION_JSON_WHITELIST_PATH:-.}/authenticate.json
        read_only: true
      - type: bind
        source: ${AUTHENTICATION_JSON_WHITELIST_PATH:-.}/build.gradle
        target: ${BUILD_GRADLE_DEPENDENCIES_PATH:-.}/${AUTHENTICATION_JSON_WHITELIST_PATH:-.}/build.gradle
        read_only: true
    environment:
      AUTHENTICATION_JSON_WHITELIST_PATH: ${AUTHENTICATION_JSON_WHITELIST_PATH}