version: '3.7'
services:
  cas_server:
    expose:
      - 8443
    volumes: 
      - type: bind
        source: ${TICKET_REGISTRY_HAZELCAST_PATH:-.}/cas.yml
        target: ${CONFIG_PATH:-.}/${TICKET_REGISTRY_HAZELCAST}.yml
        read_only: true
      - type: bind
        source: ${TICKET_REGISTRY_HAZELCAST_PATH:-.}/build.gradle
        target: ${BUILD_GRADLE_DEPENDENCIES_PATH:-.}/${TICKET_REGISTRY_HAZELCAST_PATH:-.}/build.gradle
        read_only: true
    environment:
      TICKET_REGISTRY_HAZELCAST: ${TICKET_REGISTRY_HAZELCAST}
      