version: '3.7'
services:
  cas_server:
    volumes: 
      - type: bind
        source: ${PROTOCOL_PASSWORDLESS_EMAIL_PATH:-.}/cas.yml
        target: ${CONFIG_PATH:-.}/${PROTOCOL_PASSWORDLESS_EMAIL}.yml
        read_only: true
      - type: bind
        source: ${PROTOCOL_PASSWORDLESS_EMAIL_PATH:-.}/build.gradle
        target: ${BUILD_GRADLE_DEPENDENCIES_PATH:-.}/${PROTOCOL_PASSWORDLESS_EMAIL_PATH:-.}/build.gradle
        read_only: true
    environment:
      SENT_TO_EMAIL: fvz88112@eveav.com