version: '3.7'
services:
  cas:
    volumes: 
      - type: bind
        source: ${SERVICE_REGISTRY_JSON_PATH:-.}/cas.yml
        target: ${CONFIG_PROPERTIES_PATH:-.}/${SERVICE_REGISTRY_JSON}.yml
      - type: bind
        source: ${SERVICE_REGISTRY_JSON_PATH:-.}/sample.json
        target: ${SERVICES_PATH:-.}/${SERVICE_REGISTRY_JSON}-sample-1001.json
      - type: bind
        source: ${SERVICE_REGISTRY_JSON_PATH:-.}/build.gradle
        target: ${BUILD_GRADLE_DEPENDENCIES_PATH:-.}/${SERVICE_REGISTRY_JSON_PATH:-.}/build.gradle
    environment:
      SERVICE_REGISTRY_JSON_PATH: ${SERVICE_REGISTRY_JSON_PATH}